language: python
cache: pip

python:
  - 3.4
  - 3.5

env:
  - TOXENV=dj111-wt20

# Matrix of build options
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=isort,flake8,docs

install:
  - pip install --upgrade pip wheel tox setuptools

script:
  - tox

# vim: sw=2
